import type { SoundtrackPack } from "@soundweave/schema";

// ── Minimal Pack — smallest valid pack ──

export const minimalPack: SoundtrackPack = {
  meta: {
    id: "minimal-pack",
    name: "Minimal Pack",
    version: "1.0.0",
    description: "The smallest valid soundtrack pack — one asset, one stem, one scene.",
    author: "soundweave",
    tags: ["minimal", "tutorial"],
    schemaVersion: "1",
  },
  assets: [
    {
      id: "asset-drone",
      name: "Ambient Drone",
      src: "audio/drone.ogg",
      kind: "loop",
      durationMs: 16000,
      bpm: 60,
      key: "Cm",
    },
  ],
  stems: [
    {
      id: "stem-drone",
      name: "Drone Layer",
      assetId: "asset-drone",
      role: "base",
      loop: true,
    },
  ],
  scenes: [
    {
      id: "scene-ambient",
      name: "Ambient",
      category: "exploration",
      layers: [{ stemId: "stem-drone", required: true }],
    },
  ],
  bindings: [
    {
      id: "bind-ambient",
      name: "Default Ambient",
      sceneId: "scene-ambient",
      conditions: [{ field: "mode", op: "eq", value: "exploration" }],
      priority: 0,
    },
  ],
  transitions: [],
};

// ── Combat Escalation Pack — combat → boss → victory progression ──

export const combatEscalationPack: SoundtrackPack = {
  meta: {
    id: "combat-escalation-pack",
    name: "Combat Escalation Pack",
    version: "1.0.0",
    description:
      "A multi-phase combat pack: patrol → skirmish → boss → victory with layered stems and transition stingers.",
    author: "soundweave",
    tags: ["combat", "boss", "escalation", "rpg"],
    schemaVersion: "1",
  },
  assets: [
    {
      id: "asset-patrol-base",
      name: "Patrol Base",
      src: "audio/patrol-base.ogg",
      kind: "loop",
      durationMs: 16000,
      bpm: 100,
      key: "Dm",
    },
    {
      id: "asset-patrol-perc",
      name: "Patrol Percussion",
      src: "audio/patrol-perc.ogg",
      kind: "loop",
      durationMs: 16000,
      bpm: 100,
    },
    {
      id: "asset-skirmish-base",
      name: "Skirmish Base",
      src: "audio/skirmish-base.ogg",
      kind: "loop",
      durationMs: 8000,
      bpm: 130,
      key: "Em",
    },
    {
      id: "asset-skirmish-strings",
      name: "Skirmish Strings",
      src: "audio/skirmish-strings.ogg",
      kind: "loop",
      durationMs: 8000,
      bpm: 130,
      key: "Em",
    },
    {
      id: "asset-boss-base",
      name: "Boss Base",
      src: "audio/boss-base.ogg",
      kind: "loop",
      durationMs: 8000,
      bpm: 160,
      key: "Gm",
    },
    {
      id: "asset-boss-choir",
      name: "Boss Choir",
      src: "audio/boss-choir.ogg",
      kind: "loop",
      durationMs: 8000,
      bpm: 160,
      key: "Gm",
    },
    {
      id: "asset-victory-fanfare",
      name: "Victory Fanfare",
      src: "audio/victory-fanfare.ogg",
      kind: "oneshot",
      durationMs: 5000,
    },
    {
      id: "asset-stinger-engage",
      name: "Engage Stinger",
      src: "audio/stinger-engage.ogg",
      kind: "stinger",
      durationMs: 1200,
    },
    {
      id: "asset-stinger-boss",
      name: "Boss Stinger",
      src: "audio/stinger-boss.ogg",
      kind: "stinger",
      durationMs: 2000,
    },
  ],
  stems: [
    {
      id: "stem-patrol-base",
      name: "Patrol Base",
      assetId: "asset-patrol-base",
      role: "base",
      loop: true,
    },
    {
      id: "stem-patrol-perc",
      name: "Patrol Percussion",
      assetId: "asset-patrol-perc",
      role: "accent",
      loop: true,
      mutedByDefault: true,
      gainDb: -2,
    },
    {
      id: "stem-skirmish-base",
      name: "Skirmish Base",
      assetId: "asset-skirmish-base",
      role: "combat",
      loop: true,
    },
    {
      id: "stem-skirmish-strings",
      name: "Skirmish Strings",
      assetId: "asset-skirmish-strings",
      role: "danger",
      loop: true,
      mutedByDefault: true,
    },
    {
      id: "stem-boss-base",
      name: "Boss Base",
      assetId: "asset-boss-base",
      role: "boss",
      loop: true,
    },
    {
      id: "stem-boss-choir",
      name: "Boss Choir",
      assetId: "asset-boss-choir",
      role: "boss",
      loop: true,
      gainDb: -4,
    },
    {
      id: "stem-victory",
      name: "Victory Fanfare",
      assetId: "asset-victory-fanfare",
      role: "recovery",
      loop: false,
    },
  ],
  scenes: [
    {
      id: "scene-patrol",
      name: "Patrol",
      category: "exploration",
      layers: [
        { stemId: "stem-patrol-base", required: true, startMode: "immediate" },
        { stemId: "stem-patrol-perc", startMode: "next-bar" },
      ],
      fallbackSceneId: "scene-patrol",
      tags: ["outdoor"],
    },
    {
      id: "scene-skirmish",
      name: "Skirmish",
      category: "combat",
      layers: [
        { stemId: "stem-skirmish-base", required: true },
        { stemId: "stem-skirmish-strings" },
      ],
      fallbackSceneId: "scene-patrol",
    },
    {
      id: "scene-boss",
      name: "Boss Fight",
      category: "boss",
      layers: [
        { stemId: "stem-boss-base", required: true },
        { stemId: "stem-boss-choir" },
      ],
      fallbackSceneId: "scene-skirmish",
    },
    {
      id: "scene-victory",
      name: "Victory",
      category: "victory",
      layers: [{ stemId: "stem-victory", required: true }],
      fallbackSceneId: "scene-patrol",
    },
  ],
  bindings: [
    {
      id: "bind-patrol",
      name: "Patrol Mode",
      sceneId: "scene-patrol",
      conditions: [{ field: "inCombat", op: "eq", value: false }],
      priority: 0,
    },
    {
      id: "bind-skirmish",
      name: "Skirmish Engaged",
      sceneId: "scene-skirmish",
      conditions: [
        { field: "inCombat", op: "eq", value: true },
        { field: "boss", op: "eq", value: false },
      ],
      priority: 10,
    },
    {
      id: "bind-boss",
      name: "Boss Encounter",
      sceneId: "scene-boss",
      conditions: [
        { field: "inCombat", op: "eq", value: true },
        { field: "boss", op: "eq", value: true },
      ],
      priority: 20,
    },
    {
      id: "bind-victory",
      name: "Victory Event",
      sceneId: "scene-victory",
      conditions: [{ field: "victory", op: "eq", value: true }],
      priority: 30,
      stopProcessing: true,
    },
  ],
  transitions: [
    {
      id: "trans-patrol-to-skirmish",
      name: "Patrol → Skirmish",
      fromSceneId: "scene-patrol",
      toSceneId: "scene-skirmish",
      mode: "stinger-then-switch",
      stingerAssetId: "asset-stinger-engage",
      durationMs: 1200,
    },
    {
      id: "trans-skirmish-to-boss",
      name: "Skirmish → Boss",
      fromSceneId: "scene-skirmish",
      toSceneId: "scene-boss",
      mode: "stinger-then-switch",
      stingerAssetId: "asset-stinger-boss",
      durationMs: 2000,
    },
    {
      id: "trans-boss-to-victory",
      name: "Boss → Victory",
      fromSceneId: "scene-boss",
      toSceneId: "scene-victory",
      mode: "immediate",
    },
    {
      id: "trans-victory-to-patrol",
      name: "Victory → Patrol",
      fromSceneId: "scene-victory",
      toSceneId: "scene-patrol",
      mode: "crossfade",
      durationMs: 3000,
    },
    {
      id: "trans-skirmish-to-patrol",
      name: "Skirmish → Patrol (disengage)",
      fromSceneId: "scene-skirmish",
      toSceneId: "scene-patrol",
      mode: "crossfade",
      durationMs: 2000,
    },
  ],
};

// ── Starter Adventure Pack ──

export const starterPack: SoundtrackPack = {
  meta: {
    id: "starter-pack",
    name: "Starter Adventure Pack",
    version: "1.0.0",
    description: "A basic exploration and combat soundtrack pack.",
    author: "soundweave",
    tags: ["starter", "rpg"],
    schemaVersion: "1",
  },
  assets: [
    {
      id: "asset-explore-base",
      name: "Exploration Base",
      src: "audio/explore-base.ogg",
      kind: "loop",
      durationMs: 16000,
      bpm: 90,
      key: "Am",
    },
    {
      id: "asset-explore-accent",
      name: "Exploration Accent",
      src: "audio/explore-accent.ogg",
      kind: "loop",
      durationMs: 16000,
      bpm: 90,
      loopStartMs: 0,
      loopEndMs: 16000,
    },
    {
      id: "asset-tension-base",
      name: "Tension Base",
      src: "audio/tension-base.ogg",
      kind: "loop",
      durationMs: 8000,
      bpm: 110,
      key: "Dm",
    },
    {
      id: "asset-combat-base",
      name: "Combat Base",
      src: "audio/combat-base.ogg",
      kind: "loop",
      durationMs: 8000,
      bpm: 140,
      key: "Em",
    },
    {
      id: "asset-combat-danger",
      name: "Combat Danger Layer",
      src: "audio/combat-danger.ogg",
      kind: "loop",
      durationMs: 8000,
      bpm: 140,
    },
    {
      id: "asset-victory-fanfare",
      name: "Victory Fanfare",
      src: "audio/victory-fanfare.ogg",
      kind: "oneshot",
      durationMs: 4000,
    },
    {
      id: "asset-stinger-combat",
      name: "Combat Stinger",
      src: "audio/stinger-combat.ogg",
      kind: "stinger",
      durationMs: 1500,
    },
    {
      id: "asset-safe-ambient",
      name: "Safe Zone Ambient",
      src: "audio/safe-ambient.ogg",
      kind: "ambient",
      durationMs: 30000,
      tags: ["calm", "town"],
    },
  ],
  stems: [
    {
      id: "stem-explore-base",
      name: "Explore Base",
      assetId: "asset-explore-base",
      role: "base",
      loop: true,
    },
    {
      id: "stem-explore-accent",
      name: "Explore Accent",
      assetId: "asset-explore-accent",
      role: "accent",
      loop: true,
      mutedByDefault: true,
      gainDb: -3,
    },
    {
      id: "stem-tension-base",
      name: "Tension Base",
      assetId: "asset-tension-base",
      role: "danger",
      loop: true,
    },
    {
      id: "stem-combat-base",
      name: "Combat Base",
      assetId: "asset-combat-base",
      role: "combat",
      loop: true,
    },
    {
      id: "stem-combat-danger",
      name: "Combat Danger",
      assetId: "asset-combat-danger",
      role: "danger",
      loop: true,
      mutedByDefault: true,
    },
    {
      id: "stem-victory",
      name: "Victory Fanfare",
      assetId: "asset-victory-fanfare",
      role: "recovery",
      loop: false,
    },
    {
      id: "stem-safe-ambient",
      name: "Safe Ambient",
      assetId: "asset-safe-ambient",
      role: "base",
      loop: true,
    },
  ],
  scenes: [
    {
      id: "scene-exploration",
      name: "Exploration",
      category: "exploration",
      layers: [
        {
          stemId: "stem-explore-base",
          required: true,
          startMode: "immediate",
        },
        { stemId: "stem-explore-accent", startMode: "next-bar" },
      ],
      fallbackSceneId: "scene-safe-zone",
      tags: ["outdoor", "default"],
    },
    {
      id: "scene-tension",
      name: "Rising Tension",
      category: "tension",
      layers: [{ stemId: "stem-tension-base", required: true }],
      fallbackSceneId: "scene-exploration",
    },
    {
      id: "scene-combat",
      name: "Combat",
      category: "combat",
      layers: [
        { stemId: "stem-combat-base", required: true },
        { stemId: "stem-combat-danger" },
      ],
      fallbackSceneId: "scene-tension",
    },
    {
      id: "scene-victory",
      name: "Victory",
      category: "victory",
      layers: [{ stemId: "stem-victory", required: true }],
      fallbackSceneId: "scene-exploration",
    },
    {
      id: "scene-safe-zone",
      name: "Safe Zone",
      category: "safe-zone",
      layers: [{ stemId: "stem-safe-ambient", required: true }],
      tags: ["town", "rest"],
    },
  ],
  bindings: [
    {
      id: "bind-explore",
      name: "Explore Mode",
      sceneId: "scene-exploration",
      conditions: [{ field: "mode", op: "eq", value: "exploration" }],
      priority: 0,
    },
    {
      id: "bind-tension",
      name: "Danger Rising",
      sceneId: "scene-tension",
      conditions: [{ field: "danger", op: "gte", value: 0.5 }],
      priority: 10,
    },
    {
      id: "bind-combat",
      name: "In Combat",
      sceneId: "scene-combat",
      conditions: [{ field: "inCombat", op: "eq", value: true }],
      priority: 20,
    },
    {
      id: "bind-victory",
      name: "Victory Event",
      sceneId: "scene-victory",
      conditions: [{ field: "victory", op: "eq", value: true }],
      priority: 30,
      stopProcessing: true,
    },
    {
      id: "bind-safe",
      name: "Safe Zone",
      sceneId: "scene-safe-zone",
      conditions: [{ field: "safeZone", op: "eq", value: true }],
      priority: 5,
    },
  ],
  transitions: [
    {
      id: "trans-explore-to-tension",
      name: "Explore → Tension",
      fromSceneId: "scene-exploration",
      toSceneId: "scene-tension",
      mode: "crossfade",
      durationMs: 2000,
    },
    {
      id: "trans-tension-to-combat",
      name: "Tension → Combat",
      fromSceneId: "scene-tension",
      toSceneId: "scene-combat",
      mode: "stinger-then-switch",
      stingerAssetId: "asset-stinger-combat",
      durationMs: 1500,
    },
    {
      id: "trans-combat-to-victory",
      name: "Combat → Victory",
      fromSceneId: "scene-combat",
      toSceneId: "scene-victory",
      mode: "immediate",
    },
    {
      id: "trans-victory-to-explore",
      name: "Victory → Explore",
      fromSceneId: "scene-victory",
      toSceneId: "scene-exploration",
      mode: "cooldown-fade",
      durationMs: 3000,
    },
  ],
};

// ── Example pack registry ──

export const examplePacks = [
  { id: "minimal-pack", name: "Minimal Pack", pack: minimalPack },
  { id: "starter-pack", name: "Starter Adventure Pack", pack: starterPack },
  { id: "combat-escalation-pack", name: "Combat Escalation Pack", pack: combatEscalationPack },
] as const;
